FROM golang:1.23.4

ENV config=docker

#ENV TZ=Europe/Vilnius #TIMEZONE

#RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /app

COPY ./ /app

RUN go mod download

RUN go get github.com/githubnemo/CompileDaemon

EXPOSE 5000

ENTRYPOINT CompileDaemon --build="go build sso/cmd/auth/main.go" --command="./main --config /sso/config/local.yaml"